### PR TITLE
Progress steps

### PR DESCRIPTION
**Pull request by aelanman**
Supplements the progbar functionality with a "steps" option when pyuvsim is run as a batch job. The progress bar doesn't look nice when written to log files instead of the stdout, so this lets you write progress to files. It checks for an environmental variable "PYUVSIM_BATCH_JOB" to decide which to use.

### CODE REVIEW

**Comment by aelanman** [comment]
Is it not passing coveralls because I didn't write a unit test for the progsteps class?

**Comment by bhazelton** [comment]
I'm not sure, I'm looking at the coveralls settings and there's not a set COVERAGE THRESHOLD FOR FAILURE or COVERAGE DECREASE THRESHOLD FOR FAILURE, so I'm not sure why it's failing. We probably do want to set those eventually...

**Comment by bhazelton** [comment]
I'm inclined to merge this and make an issue about increasing test coverage. What do you think @jpober?

**Comment by jpober** [comment]
Sounds good to me @bhazelton

**Pull request merged**
